dist: xenial
cache:
  directories:
  - $HOME/.m2
language: java
jdk: openjdk11
install:
  - mvn -B -Pdeploy --settings .travis-settings.xml -V dependency:go-offline
script:
  - mvn -B -Pdeploy --settings .travis-settings.xml -Dgpg.skip=true verify
  - java -jar target/benchmarks.jar -foe true -wi 0 -i 1 -f 1 -p num=512
notifications:
  email:
    - ben.alex@acegi.com.au
    - stoffe@gmail.com
